raw_train_file: "data/train.txt"
raw_dev_file: "data/dev.txt"
raw_test_file: "data/test.txt"
train_sample_file_save: "data/train_sample.txt"
dev_sample_file_save: "data/dev_sample.txt"
test_sample_file_save: "data/test_sample.txt"
train_text_file_save: "data/train.src"
dev_text_file_save: "data/dev.src"
test_text_file_save: "data/test.src"
train_topic_file_save: "data/train_topic.txt"
dev_topic_file_save: "data/dev_topic.txt"
test_topic_file_save: "data/test_topic.txt"
train_tgt_file: "data/train.tgt"
dev_tgt_file: "data/dev.tgt"
test_tgt_file: "data/test.tgt"
log_file: "outputs/log/log.txt"