# Model
model: "outputs/checkpoints/2019-5-1-transformer-17w_step_13300.pt"
avg_raw_probs: "false"
# Data
data_type: "text"
src: "data/all.src"
tgt: "data/all.tgt"
output: "outputs/pred.txt"
report_bleu: "false"
report_rouge: "false"
# Random sampling
random_sampling_topk: 1
random_sampling_temp: 1.
seed: 829
# Beam
beam_size: 2
min_length: 4
max_length: 100
replace_unk: "true"
batch_size: 16
gpu: 0
#alpha: 0
#beta: 0
#length_penalty: "wu"
#stepwise_penalty: 'true'
block_ngram_repeat: 0
#coverage_penalty: "wu"
dynamic_dict: "true"
share_vocab: "true"
